#pragma once
      
#define ETL_TARGET_DEVICE_GENERIC
#define ETL_TARGET_OS_NONE
#define ETL_COMPILER_GENERIC
#define ETL_CPP11_SUPPORTED 1
#define ETL_CPP14_SUPPORTED 1
#define ETL_CPP17_SUPPORTED 1
#define ETL_NO_NULLPTR_SUPPORT 0
#define ETL_NO_LARGE_CHAR_SUPPORT 0
#define ETL_CPP11_TYPE_TRAITS_IS_TRIVIAL_SUPPORTED 1
#define ETL_VERBOSE_ERRORS 1

// #define ETL_CPP20_SUPPORTED 1
#define ETL_DEBUG 1
#define ETL_LOG_ERRORS 1
#define ETL_THROW_EXCEPTIONS 1
#define ETL_VERBOSE_ERRORS 1
#define ETL_CHECK_PUSH_POP 1
#define ETL_POLYMORPHIC_CONTAINERS 1
// #define ETL_ISTRING_REPAIR_ENABLE 1
// #define ETL_IVECTOR_REPAIR_ENABLE 1
// #define ETL_IDEQUE_REPAIR_ENABLE 1
// #define ETL_ICIRCULAR_BUFFER_REPAIR_ENABLE 1
// #define ETL_IN_UNIT_TEST 1
// #define ETL_DEBUG_COUNT 1
// #define ETL_ARRAY_VIEW_IS_MUTABLE 1

// #define ETL_HAS_ATOMIC 1
// #define ETL_HAS_VIRTUAL_MESSAGES 1
// #define ETL_MESSAGE_ROUTER_INCLUDED 1

// #define ETL_MESSAGE_TIMER_USE_ATOMIC_LOCK 1
// #define ETL_CALLBACK_TIMER_USE_ATOMIC_LOCK 1

// #define ETL_POLYMORPHIC_RANDOM 1

// #define ETL_POLYMORPHIC_BITSET 1
// #define ETL_POLYMORPHIC_DEQUE 1
// #define ETL_POLYMORPHIC_FLAT_MAP 1
// #define ETL_POLYMORPHIC_FLAT_MULTIMAP 1
// #define ETL_POLYMORPHIC_FLAT_SET
// #define ETL_POLYMORPHIC_FLAT_MULTISET
// #define ETL_POLYMORPHIC_FORWARD_LIST
// #define ETL_POLYMORPHIC_LIST
// #define ETL_POLYMORPHIC_MAP
// #define ETL_POLYMORPHIC_MULTIMAP
// #define ETL_POLYMORPHIC_SET
// #define ETL_POLYMORPHIC_MULTISET
// #define ETL_POLYMORPHIC_QUEUE
// #define ETL_POLYMORPHIC_STACK
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MAP
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MULTIMAP
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_SET
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MULTISET
// #define ETL_POLYMORPHIC_UNORDERED_MAP
// #define ETL_POLYMORPHIC_UNORDERED_MULTIMAP
// #define ETL_POLYMORPHIC_UNORDERED_SET
// #define ETL_POLYMORPHIC_UNORDERED_MULTISET
// #define ETL_POLYMORPHIC_STRINGS
// #define ETL_POLYMORPHIC_POOL
// #define ETL_POLYMORPHIC_VECTOR
// #define ETL_POLYMORPHIC_INDIRECT_VECTOR
