// #pragma once
// #include "etl/profiles/cpp17.h"
// #include "etl/profiles/gcc_generic.h"

// #define ETL_THROW_EXCEPTIONS
// #define ETL_VERBOSE_ERRORS
// #define ETL_CHECK_PUSH_POP
// #define ETL_ISTRING_REPAIR_ENABLE
// #define ETL_IVECTOR_REPAIR_ENABLE
// #define ETL_IDEQUE_REPAIR_ENABLE
// #define ETL_ICIRCULAR_BUFFER_REPAIR_ENABLE
// #define ETL_IN_UNIT_TEST
// #define ETL_DEBUG_COUNT
// #define ETL_ARRAY_VIEW_IS_MUTABLE

// #define ETL_HAS_ATOMIC 1
// #define ETL_HAS_VIRTUAL_MESSAGES 1
// #define ETL_MESSAGE_ROUTER_INCLUDED

// #define ETL_MESSAGE_TIMER_USE_ATOMIC_LOCK
// #define ETL_CALLBACK_TIMER_USE_ATOMIC_LOCK

// #define ETL_POLYMORPHIC_RANDOM

// #define ETL_POLYMORPHIC_BITSET
// #define ETL_POLYMORPHIC_DEQUE
// #define ETL_POLYMORPHIC_FLAT_MAP
// #define ETL_POLYMORPHIC_FLAT_MULTIMAP
// #define ETL_POLYMORPHIC_FLAT_SET
// #define ETL_POLYMORPHIC_FLAT_MULTISET
// #define ETL_POLYMORPHIC_FORWARD_LIST
// #define ETL_POLYMORPHIC_LIST
// #define ETL_POLYMORPHIC_MAP
// #define ETL_POLYMORPHIC_MULTIMAP
// #define ETL_POLYMORPHIC_SET
// #define ETL_POLYMORPHIC_MULTISET
// #define ETL_POLYMORPHIC_QUEUE
// #define ETL_POLYMORPHIC_STACK
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MAP
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MULTIMAP
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_SET
// #define ETL_POLYMORPHIC_REFERENCE_FLAT_MULTISET
// #define ETL_POLYMORPHIC_UNORDERED_MAP
// #define ETL_POLYMORPHIC_UNORDERED_MULTIMAP
// #define ETL_POLYMORPHIC_UNORDERED_SET
// #define ETL_POLYMORPHIC_UNORDERED_MULTISET
// #define ETL_POLYMORPHIC_STRINGS
// #define ETL_POLYMORPHIC_POOL
// #define ETL_POLYMORPHIC_VECTOR
// #define ETL_POLYMORPHIC_INDIRECT_VECTOR
